from enum import StrEnum


class ConversationState(StrEnum):
    GREETING = "GREETING"
    DISCLOSURE_AND_CONSENT = "DISCLOSURE_AND_CONSENT"
    UNDERSTAND_REASON_FOR_CALL = "UNDERSTAND_REASON_FOR_CALL"
    IDENTIFY_CARE_RECIPIENT = "IDENTIFY_CARE_RECIPIENT"
    ASSESS_CARE_NEEDS = "ASSESS_CARE_NEEDS"
    ASSESS_URGENCY_AND_SAFETY = "ASSESS_URGENCY_AND_SAFETY"
    COLLECT_LOCATION_REQUIREMENTS = "COLLECT_LOCATION_REQUIREMENTS"
    COLLECT_FINANCIAL_REQUIREMENTS = "COLLECT_FINANCIAL_REQUIREMENTS"
    COLLECT_PREFERENCES = "COLLECT_PREFERENCES"
    UNDERSTAND_DECISION_PROCESS = "UNDERSTAND_DECISION_PROCESS"
    COLLECT_CALLER_CONTACT = "COLLECT_CALLER_CONTACT"
    CONFIRM_SUMMARY = "CONFIRM_SUMMARY"
    MATCH_PROVIDERS = "MATCH_PROVIDERS"
    EXPLAIN_RECOMMENDATIONS = "EXPLAIN_RECOMMENDATIONS"
    CAPTURE_FOLLOWUP_CONSENT = "CAPTURE_FOLLOWUP_CONSENT"
    END_OR_HUMAN_HANDOFF = "END_OR_HUMAN_HANDOFF"


class CareType(StrEnum):
    HOSPICE = "hospice"
    HOME_CARE = "home_care"
    ASSISTED_LIVING = "assisted_living"
    MEMORY_CARE = "memory_care"
    SKILLED_NURSING = "skilled_nursing"
    RESPITE_CARE = "respite_care"


class ProviderType(StrEnum):
    HOME_CARE = "home_care"
    ASSISTED_LIVING = "assisted_living"
    MEMORY_CARE = "memory_care"
    SKILLED_NURSING = "skilled_nursing"
    HOSPICE = "hospice"
    RESPITE_CARE = "respite_care"
